### ISSUE TITLE
Can't find openMVG_main_openMVGSpherical2Cubic

### ISSUE THREAD

**Issue by iamwangyabin** [openMVG/Image_datasets#1]
I follow the INSTALL.md to install openMVG ,but can't find openMVG_main_openMVGSpherical2Cubic

**Comment by pmoulon** [comment]
I must add it to the cmake install target. 
Thank you for your feedback.
For now please use the one you just compiled in your build folder.

**Comment by pmoulon** [comment]
The binary should be exported see here https://github.com/openMVG/openMVG/blob/develop_spherical_to_cubic/src/software/SfM/export/CMakeLists.txt#L136

Please note that you have to use the develop/develop_spherical_to_cubic branch to see it

**Comment by humfrey28whu** [comment]
> The binary should be exported see here https://github.com/openMVG/openMVG/blob/develop_spherical_to_cubic/src/software/SfM/export/CMakeLists.txt#L136
> 
> Please note that you have to use the develop/develop_spherical_to_cubic branch to see it

Hello! I "git pull" from the "develop_spherical_to_cubic branch", and I cmake it with vcpkg, using cmdline "cmake -G "Visual Studio 14 2015 Win64" ..\src\ -DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake -DOpenMVG_USE_OPENCV=ON". However I get following errors:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CLPSOLVER_LIBRARY
    linked by target "openMVG_linearProgramming" in directory E:/openMVG/src/openMVG/linearProgramming
OSICLP_LIBRARY
    linked by target "openMVG_linearProgramming" in directory E:/openMVG/src/openMVG/linearProgramming

How can I solve it? Thank you!

**Comment by pmoulon** [comment]
It is a known issue in the past develop branch. You can checkout `develop` and this problem is now fixed.
The other way to go around this issue is to remove all the files in the path where you ask cmake to build the solution.

**Comment by humfrey28whu** [comment]
> It is a known issue in the past develop branch. You can checkout `develop` and this problem is now fixed.
> The other way to go around this issue is to remove all the files in the path where you ask cmake to build the solution.

Thank you! I checkout the `develop` branch and it builds successfully. But the second way is not work. In addition, I want to ask for some tips about `cmake` and `git`. 
When I `git pull` from the remote to update the code in native, I'll always do like this:
·Open the visual studio 2015
·Batch build->build ZERO_CHECK
·Batch build->build ALL_BUILD
·Batch build->build INSTALL

However, it takes a long time. So I want to ask if there was a simpler way to do the work?
Thank you very much!
